GLOBAL {
	INPUTNAME "au.rom";
	CPU "W65C02";
	COMMENTS 3;
	STARTADDR $0000;
};
SEGMENT { START $0000; END $0FF9; NAME "RAM"; };
SEGMENT { START $0FFA; END $0FFF; NAME "VECTORS"; };

RANGE { START $0FFA; END $0FFF; TYPE AddrTable; };

LABEL { NAME "ACC"; ADDR $0; };
LABEL { NAME "V0"; ADDR $10; SIZE $7; };
LABEL { NAME "V1"; ADDR $17; SIZE $7; };
LABEL { NAME "V2"; ADDR $1E; SIZE $7; };
LABEL { NAME "V3"; ADDR $25; SIZE $7; };
LABEL { NAME "DAC"; ADDR $8000; SIZE $8000; };
